//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account()
        {
            this.creditoraccounts = new HashSet<creditoraccount>();
            this.debtoraccounts = new HashSet<debtoraccount>();
        }
    
        public string accountnumber { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> awarddate { get; set; }
        public string state { get; set; }
        public string status { get; set; }
        public Nullable<double> apr { get; set; }
        public Nullable<double> courtcost { get; set; }
        public Nullable<double> servicecost { get; set; }
        public string userassigned { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<creditoraccount> creditoraccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<debtoraccount> debtoraccounts { get; set; }
    }
}
