//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class debtoraccount
    {
        public int id { get; set; }
        public int debtor { get; set; }
        public string account { get; set; }
    
        public virtual debtor debtor1 { get; set; }
    }
}
